# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ed82501c79d6d0938c72f9e7c3cbf9e3af78e9a320b236dfef5a390e32022916e5e27b0919b5de886524eac3b7e2cf0f087bd9c8eb3fbb4cca975a0b559dbb8

test:
  secret_key_base: 774b663a953df1d72e50b72c74478f501d540b23ecfa1e220ed823ec9fb72ba41c5871583daf59fb1463eb665d81b0bc0ebfdca3a6048b90651f7088525de69e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
